### PR TITLE
Small refactor of common.utils adding Swapping and chainable

### PR DESCRIPTION
**Pull request by egparedes**
Add the`Swapping` class inside `model.common.utils` as a generic utility for double buffering. Additionally, rename the `builder` class  to `chainable` and move it to the same `_common` module as `Swapping`.

### CODE REVIEW

**Review by halungge — APPROVED** [review]
LGTM
I assume you did not touch the `comm/utils/gt4py_field_allocation.py` to keep it small? or should we add the allocation functions there as well to the `__init__.py`?

**Comment by egparedes** [comment]
> LGTM I assume you did not touch the `comm/utils/gt4py_field_allocation.py` to keep it small? or should we add the allocation functions there as well to the `__init__.py`?

Yes, I left that module untouched to keep this PR simple and avoid collisions with on-going work (e.g. changes in array allocation by @nfarabullini)

**Comment by egparedes** [comment]
cscs-ci run default

**Comment by egparedes** [comment]
launch jenkins spack

**Comment by egparedes** [comment]
cscs-ci run default

**Comment by egparedes** [comment]
launch jenkins spack

**Comment by egparedes** [comment]
cscs-ci run default

**Comment by egparedes** [comment]
launch jenkins spack

**Comment by egparedes** [comment]
launch jenkins spack

**Comment by egparedes** [comment]
launch jenkins spack

**Pull request merged**
