### PR TITLE
Remove cached program

### PR DESCRIPTION
**Pull request by samkellerhals**
Fixes to adapt to changes introduced in https://github.com/GridTools/gt4py/pull/1545

In the future we should use `FrozenProgram` for caching instead of `CachedPrograms`.

Test will need to be fixed as soon as fixes from https://github.com/GridTools/gt4py/issues/1582 are merged.

### CODE REVIEW

**Comment by samkellerhals** [comment]
cscs-ci run default

**Comment by samkellerhals** [comment]
launch jenkins spack

**Review by kotsaloscv — APPROVED** [review]
Looks good!

**Comment by samkellerhals** [comment]
cscs-ci run default

**Comment by samkellerhals** [comment]
cscs-ci run default

**Comment by samkellerhals** [comment]
cscs-ci run default

**Pull request merged**
