### PR TITLE
Removed i_am_accel_node from Liskov code generator and examples

### PR DESCRIPTION
**Pull request by muellch**
Self explanatory ...

### CODE REVIEW

**Comment by muellch** [comment]
cscs-ci run default

**Comment by muellch** [comment]
launch jenkins spack

**Comment by muellch** [comment]
launch jenkins spack

**Review by huppd — APPROVED** [review]
Looks good to me. Nice cleanup.

**Comment by muellch** [comment]
launch jenkins spack

**Comment by muellch** [comment]
cscs-ci run default

**Comment by muellch** [comment]
cscs-ci run default

**Comment by muellch** [comment]
launch jenkins spack

**Comment by muellch** [comment]
launch jenkins spack

**Pull request merged**
