### PR TITLE
Gitignore_updates

### PR DESCRIPTION
**Pull request by jcanton**
update gitignore to ignore:
 - .vscode in case it is a symlink and not just a folder
 - sphinx rst files

### CODE REVIEW

**Review by jcanton — COMMENTED** [review]
cscs-ci run default

**Review by jcanton — COMMENTED** [review]
launch jenkins spack

**Review by nfarabullini — APPROVED** [review]

**Review by samkellerhals — APPROVED** [review]

**Review by OngChia — APPROVED** [review]

**Comment by jcanton** [comment]
cscs-ci run default

**Comment by jcanton** [comment]
launch jenkins spack

**Pull request merged**
