### PR TITLE
Create AUTHORS.md

### PR DESCRIPTION
**Pull request by havogt**
This is just copying the style from GT4Py. Feel free to change...

### CODE REVIEW

**Comment by havogt** [comment]
I just copied from GT4Py...

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
launch jenkins spack

**Review by halungge — APPROVED** [review]

**Comment by halungge** [comment]
launch jenkins spack

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
launch jenkins spack

**Comment by halungge** [comment]
cscs-ci run default

**Pull request merged**
