### PR TITLE
Offset vertical domain

### PR DESCRIPTION
**Pull request by halungge**
Introduces more flexibility for the vertical domain by allowing for a integer offset, such that essentially any vertical level can be defined: 
For example:
```python
vertical_grid.index(domain(dims.KDim, Zone.TOP, 1) = 1
```
The `VerticalGrid.index` function checks for out of bounds, i.e. index values below 0 or larger than `num_levels` or `num_levels + 1` depending on the dimension. 

### Additional changes
- moved the `IconGridError` exception class to `exceptions.py`
- fixed imports in `test_vertical.py`
- add return types in `vertical.py`

### CODE REVIEW

**Comment by halungge** [comment]
launch jenkins spack

**Comment by halungge** [comment]
cscs-ci run default

**Review by nfarabullini — APPROVED** [review]

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
launch jenkins spack

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
cscs-ci run default

**Pull request merged**
