### PR TITLE
speed up build-times

### PR DESCRIPTION
**Pull request by jonasjucker**

### CODE REVIEW

**Comment by jonasjucker** [comment]
launch jenkins spack

**Comment by jonasjucker** [comment]
launch jenkins spack

**Comment by jonasjucker** [comment]
launch jenkins spack

**Comment by jonasjucker** [comment]
launch jenkins spack

**Comment by jonasjucker** [comment]
launch jenkins spack

**Comment by jonasjucker** [comment]
launch jenkins spack

**Comment by muellch** [comment]
cscs-ci run default

**Comment by muellch** [comment]
launch jenkins spack

**Review by muellch — APPROVED** [review]
Looks good!

**Pull request merged**
