### PR TITLE
add index abstract for the vertical grid

### PR DESCRIPTION
**Pull request by halungge**
Refactoring and extension of the vertical grid:
We need a way to separate the specification of vertical indices from their explicit computation on a given vertical configuration.
In order to achieve this, a vertical `Domain` class and a enum specifying several `Zone`s is introduced. An index can then be looked up via
```python
domain = vertical.Domain(KDim, Zone.Bottom)
vertical_grid = VerticalGrid(config)
index = vertical_grid.index(domain)
``` 
Naming (eg `Zone` , `Domain` ) was chosen to match the lookup of `start_index` and `end_index` in the horizontal grid with [PR 531](https://github.com/C2SM/icon4py/pull/531)

I chose to add this to the `VerticalParams` and rename those to `VerticalGrid`

## additional changes
- fix typo in a function
- fix imports in parallel diffusion and dycore tests

### CODE REVIEW

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
launch jenkins spack

**Review by OngChia — APPROVED** [review]

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
launch jenkins spack

**Pull request merged**
