### PR TITLE
Introduced module imports for dimensions

### PR DESCRIPTION
**Pull request by nfarabullini**
removed local definition of dimensions and introduced module import -->

From: 
```python
# TODO: this will have to be removed once domain allows for imports
EdgeDim = dims.EdgeDim
KDim = dims.KDim

@field_operator
def _field_op(
	fields..,
        out=out,
        domain={
            EdgeDim: (horizontal_start, horizontal_end),
            KDim: (vertical_start, vertical_end),
        },
    )
```

To: 

```python
@field_operator
def _field_op(
	fields..,
        out=out,
        domain={
            dims.EdgeDim: (horizontal_start, horizontal_end),
            dims.KDim: (vertical_start, vertical_end),
        },
    )
```

### CODE REVIEW

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Comment by nfarabullini** [comment]
cscs-ci run default

**Comment by nfarabullini** [comment]
launch jenkins spack

**Review by egparedes — APPROVED** [review]
LGTM.

Note to myself: maybe in the future we could consider renaming the dimension symbols to drop the `Dim` suffix, since the name already contains `dims` in the module part...

**Pull request merged**
