### PR TITLE
fix the path to the stencil tests in the spack pytest config

### PR DESCRIPTION
**Pull request by halungge**
(FIX) Fix wrong test folder paths in spack build pytest config

the spack build in [SPACK-C2SM](https://github.com/C2SM/spack-c2sm) runs tests relevant for the blueline integration, among those the stencils tests. Test discovery is done via a custom pytest.ini file.

This PR fixes the paths to the stencil tests in the model packages.

### CODE REVIEW

**Comment by halungge** [comment]
launch jenkins spack

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
cscs-ci run default

**Comment by halungge** [comment]
launch jenkins spack

**Review by nfarabullini — APPROVED** [review]

**Pull request merged**
